version: "2.1"

services:
  web:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"