version: "2.2"

services:
  web:
    build:
      context: ./
      dockerfile: docker/web/dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/db/create_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"